In [ ]:
from sklearn.ensemble import IsolationForest
from sklearn.mixture import GaussianMixture
from sklearn import preprocessing
import numpy as np
import pandas as pd

In [ ]:
OC_sc = pd.read_excel (r'/content/OC_Specialty chemicals.xlsx',index_col=0)  # import dataset
OC_mc = pd.read_excel (r'/content/OC_other machinery & equipment.xlsx',index_col=0)
OC_hf = pd.read_excel (r'/content/OC_wholeFirm.xlsx',index_col=0)
SU_hf = pd.read_excel (r'/content/SU_Whole Firms.xlsx',index_col=0)
SU_fce = pd.read_excel (r'/content/SU_flow control equipment.xlsx',index_col=0)


In [ ]:
## filling NaN with median
OC_sc = OC_sc.fillna(OC_sc.median())
OC_mc = OC_mc.fillna(OC_mc.median())
OC_hf = OC_sc.fillna(OC_hf.median())
SU_hf = OC_sc.fillna(SU_hf.median())
SU_fce = OC_sc.fillna(SU_fce.median())

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  after removing the cwd from sys.path.


In [ ]:
## standardizing dataset
scaler_1= preprocessing.StandardScaler().fit(OC_sc)
scaler_2= preprocessing.StandardScaler().fit(OC_mc)
scaler_3= preprocessing.StandardScaler().fit(OC_hf)
scaler_4= preprocessing.StandardScaler().fit(SU_hf)
scaler_5= preprocessing.StandardScaler().fit(SU_fce)

OC_sc=scaler_1.transform(OC_sc)
OC_sc=scaler_2.transform(OC_mc)
OC_sc=scaler_3.transform(OC_hf)
SU_hf=scaler_4.transform(SU_hf)
SU_fce=scaler_5.transform(SU_fce)

In [ ]:


OC_sc=np.array(OC_sc)
OC_mc=np.array(OC_mc)
OC_hf=np.array(OC_hf)
SU_hf=np.array(SU_hf)
SU_fce=np.array(SU_fce)

list_x = []
list_x.append(OC_sc)
list_x.append(OC_mc)
list_x.append(OC_hf)
list_x.append(SU_hf)
list_x.append(SU_fce)


res_x_gm = []
res_x_if = []
final_score_if = []

for x in list_x:
  gm =  GaussianMixture(n_components=2, random_state=0)
  gm.fit(x)
  res_gm = gm.predict(x)
  res_x_gm.append(res_gm)

  clf = IsolationForest(n_estimators=100,contamination=0.05,max_samples=10,max_features=10,random_state=42)
  clf.fit(x)

  res_if = clf.predict(x)
  res_x_if.append(res_if)

  score_if = clf.decision_function(x)
  final_score_if.append(score_if)

res_x_if

[array([ 1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1]),
 array([ 1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1]),
 array([ 1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1]),
 array([ 1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1]),
 array([ 1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1])]

In [ ]:
res_x_gm

[array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1]),
 array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1])]

In [ ]:
clf.predict(x)
clf.decision_function(x)

NameError: ignored

In [ ]:
gm.predict_proba(x)

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.]])