In [ ]:
from sklearn.ensemble import RandomForestRegressor
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel (r'/content/betaequity.xlsx')  # import dataset
df

In [ ]:
x = df.drop(["year","equity_beta"], axis=1)     # get x and y
y = df['equity_beta']
x

In [ ]:
# build a random forest model
regr = RandomForestRegressor(n_estimators=100, max_depth=5, random_state=0)
regr.fit(x,y)

RandomForestRegressor(max_depth=5, random_state=0)

In [ ]:
regr.predict([[1,1,1,0,0,0,0]]) # prebid strategy

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([0.8446])

In [ ]:
regr.predict([[1,0,0,0,0,0,0]]) # management group：only tobacco business

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([0.73153333])

In [ ]:
regr.predict([[1,0,1,0,0,0,0]]) # KKR

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  "X does not have valid feature names, but"


array([0.8446])

In [ ]:
# visualize one of tree
!pip install dtreeviz
from dtreeviz.trees import dtreeviz
feature_name = ["tobacco", "food", "food_expand", "container-shipping", "alcoholic_beverages", "KFC", "erengy"]
viz = dtreeviz(regr.estimators_[99], x, y,
               feature_names=feature_name,
               title="1st decision tree - House data")
viz